### ISSUE TITLE
DRY, но не везде, нипанятна

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#1]
![image](https://user-images.githubusercontent.com/101792032/182078650-c2b6d522-1299-4dba-8231-3657265749be.png)

Почему setTodoArray вызывается вместе с setStorageHandler, но не всегда? 
Почему иногда можно и не сохранять в локал?

Если нужно сохранять всегда, то тогда сделай композицию этих двух функций `updateTodos` какой-нибудь, и там вызывай эти два метода. Убери DRY короче

**Comment by VKNagibin** [comment]
9af4df39a72de0127580afc017ca1cacc85b84f3
сделяль
