### ISSUE TITLE
Просто для общего развития

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#12]
![image](https://user-images.githubusercontent.com/101792032/184809674-93d941c0-0573-42f1-a322-db6cfa0f9992.png)

Можешь не переделывать, но на заметку возьми:

1. Утилитки и все такое, что используется по всему приложению, неплохо подписывать с помощью jsDoc.
2. Имя должно соответствовать логике функции, напрашивается закинуть туда объект. Либо писать сразу реализацию, чтобы работало с чем угодно, в том числе с примитивами.

**Comment by VKNagibin** [comment]
4005c7d
