### ISSUE TITLE
Нет единого мнения в твоей голове

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#13]
![image](https://user-images.githubusercontent.com/101792032/184810107-618dd6bd-a4de-4d63-bb0a-145a05d1ac92.png)
Разделил типы по отдельным папкам, однако:
1. Где-то у тебя тип, где-то интерфейс. По сути все это интерфейсы
2. Где-то у тебя `IProps`, где-то `Props`
3. Невозможно использовать эти интерфейсы где-то вне компонента, так как при попытке заимпортировать `IProps` будет предлагать импортировать пропсы всех компонентов приложения, и будут конфликты. Лучше подписывать как `IPropsTodoButton` например, чтобы при попытке найти `IPropsTodo` поиск дальше подкидывал релевантные варианты типа `...Button` `...List` и т.д.

**Comment by VKNagibin** [comment]
22b6172
