### ISSUE TITLE
Включи подсветку в IDE и читай что она предлагает

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#2]
![image](https://user-images.githubusercontent.com/101792032/182079116-3c349232-0dd0-4f94-9af5-b1bc9defc4d7.png)

Проверь что у тебя так же подсвечивается. Если подсвечивается, то читай, обычно там дельные вещи, не считая await EventLoop :)

**Comment by VKNagibin** [comment]
да, подсвечивается. Просто я против системы
