### ISSUE TITLE
Лучше так не делать

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#3]
![image](https://user-images.githubusercontent.com/101792032/182079326-b37c6543-8967-468d-a2ff-6c6a02e7a089.png)

` prevArray.forEach(item => item.checked = true); ` 
У тебя здесь меняется только сам флажок, не нужно так делать, нарушаешь DRY

![image](https://user-images.githubusercontent.com/101792032/182079519-2a3ca8ce-8289-4296-91b3-098b24c028f3.png)

Лучше что-то подобное. Ты не повторяешь участки кода, не городишь лишнюю вложенность

**Comment by VKNagibin** [comment]
b193786
