### ISSUE TITLE
Внеси ясности

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#4]
![image](https://user-images.githubusercontent.com/101792032/182079716-83d300dd-7c78-49fb-94d2-b8173a470f62.png)

Напиши функцию `cloneShallow`, которая возврает поверхностную копию массива или объекта, и используй вместо `todoArray.slice()`, это повысит читаемость

Эту функцию закинь в утилиты, т.к. в теории она будет юзаться везде.

![image](https://user-images.githubusercontent.com/101792032/182079921-411c9419-93a4-4e20-b6c9-fa2277dec6f8.png)

**Comment by mordvinian** [comment]
Пока что можно ограничиться такой же реализацией `const cloneShallow = arr => arr.slice()`, но со временем при необходимости можно будет добавить поддержку объектов, или опционального параметра depth например. 

Функция сможет эволюционировать

**Comment by VKNagibin** [comment]
62a3391
