### ISSUE TITLE
Разбей на подфайлы

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#5]
![image](https://user-images.githubusercontent.com/101792032/182080237-a1d564af-442f-4424-b4d3-ca4d9511ca94.png)

Под каждый компонент сделай папку, в ней три файла: styled, types, component. 

Разложи каждую сущность туда, где ей место. Это повысит читаемость

**Comment by mordvinian** [comment]
Можешь не создавать types если у тебя типизируются только Props

**Comment by VKNagibin** [comment]
9af4df3
