### ISSUE TITLE
Плохо, не оптимизируется 

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#6]
![image](https://user-images.githubusercontent.com/101792032/182080683-df5a8380-14b0-4bd0-b8ca-f12c54378ec1.png)

Не надо так делать, сделай функцию `handleInput` и туда переложи всю кашу которая у тебя на onChange висит сейчас.

Читается тяжело, гораздо хуже чем handleClick который ниже

**Comment by VKNagibin** [comment]
85b84f3

**Comment by VKNagibin** [comment]
9af4df39a72de0127580afc017ca1cacc85b84f3
