### ISSUE TITLE
А зачем это переопределение? 

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-app-hooks-ts#9]
![image](https://user-images.githubusercontent.com/101792032/182081913-aebf42c7-96ce-4f29-ac8b-ffb5c0c52174.png)

**Comment by mordvinian** [comment]
Можно ж проще

**Comment by VKNagibin** [comment]
eaa0835

**Comment by mordvinian** [comment]
Я плохо объяснил. 
Зачем делать функцию `const handleDelete = (id) => props.handleDelete(id)`
если можно использовать сразу `props.handleDelete` ?

**Comment by mordvinian** [comment]
И передать эту функцию сразу в обработчики. И кода меньше, и думать меньше, и бандл весит меньше.

**Comment by VKNagibin** [comment]
43ba281
